# Generated by Django 3.0.1 on 2020-01-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_profile',
            fields=[
                ('faculty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('batchincharge', models.CharField(max_length=200)),
                ('blood_grp', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
