# Generated by Django 3.0.1 on 2020-01-13 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculty_profile',
            table='faculty_profile',
        ),
    ]
