# Generated by Django 3.0.1 on 2020-01-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20200113_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_assessment',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('batch', models.CharField(max_length=200)),
                ('asses1', models.CharField(max_length=200)),
                ('asses2', models.CharField(max_length=200)),
                ('asses3', models.CharField(max_length=200)),
                ('rank', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'faculty_assessment',
            },
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='dob',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='faculty_profile',
            name='join_date',
            field=models.CharField(max_length=200),
        ),
    ]
