# Generated by Django 3.0.1 on 2020-01-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_auto_20200114_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_attendence',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('batch', models.CharField(max_length=200)),
                ('shour', models.CharField(max_length=200)),
                ('thour', models.CharField(max_length=200)),
                ('fhour', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'faculty_attendence',
            },
        ),
    ]
