# Generated by Django 3.0.1 on 2020-01-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_faculty_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_attendence',
            name='fohour',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
