# Generated by Django 3.0.1 on 2020-01-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_faculty_attendence_fohour'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_attendence',
            name='date',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
