# Generated by Django 3.0.1 on 2020-01-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_reg',
        ),
    ]
