# Generated by Django 3.0.1 on 2020-01-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_leave',
            fields=[
                ('leave_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('from_date', models.CharField(max_length=200)),
                ('to_date', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('describ', models.CharField(max_length=200)),
            ],
        ),
    ]
