# Generated by Django 3.0.1 on 2020-01-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_leave'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student_leave',
            table='student_leave',
        ),
    ]
