# Generated by Django 3.0.1 on 2020-01-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200113_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_leave',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
