# Generated by Django 3.0.1 on 2020-01-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_leave',
            name='batch',
            field=models.CharField(default='JSD2', max_length=200),
        ),
    ]
